package me.spanchenko.dto

import kotlinx.serialization.Serializable

@Serializable
data class NoteDto(
    val id: Long = 0, // will be generated by Exposed
    val title: String,
    val content: String,
) : Dto
